namespace ReceiverController
{
    public enum StatusRequest
    {
        VolumeLevel,
        PowerStatus,
        MuteStatus,
        FunctionMode,
        ListeningModeSetting,
        ListeningMode,
        ToneStatus,
        BassStatus,
        TrebleStatus,
        TunerPresetStatus,
        TunerFreqRequest,
        MultiInputChannel,
        Zone2PowerStatus,
        Zone3PowerStatus,
        Zone2FunctionStatus,
        Zone3FunctionStatus,
        Zone2VolumeStatus,
        Zone3VolumeStatus,
        MCACCPosition,
        SBchProcessingStatus,
        XmChannel,
        PhaseControlStatus,
        SiriusChannel
    }
}